services:
  dock-med-cart:
    image: med-cart:latest
    ports:
      - 8080:8081
    environment:
      db_medcart_connection: jdbc:postgresql://host.docker.internal:5432/rc_medcarta
      db_medcart_login: postgres
      db_medcart_pass: admin
      jpa_show_sql: false