services:
  dock-medcard:
    build: .
    ports:
      - 8081:8081
    environment:
      db_medcart_connection: jdbc:postgresql://host.docker.internal:5432/rc_medcarta
      db_medcart_login: postgres
      db_medcart_pass: admin
      jpa_show_sql: false