services:
  dock-arm:
    image: dock-arm:latest
    ports:
      - 8080:8080
    environment:
      db_arm_connection: jdbc:postgresql://host.docker.internal:5432/rc_doc_test
      db_arm_login: postgres
      db_arm_pass: admin
      jpa_show_sql: false
      jwt_lifetime_days: 1
      jwt_secret: 2374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf
      security_develop_mode: true
      medcard_root_url: http://host.docker.internal:8081/api/v1

  dock-med-cart:
    image: med-cart:0.0.1
    ports:
      - 8081:8081
    environment:
      db_medcart_connection: jdbc:postgresql://host.docker.internal:5432/rc_medcarta
      db_medcart_login: postgres
      db_medcart_pass: admin
      jpa_show_sql: false

  dock-icf:
    image: icf:0.0.1
    ports:
      - 8082:8082
    environment:
      db_icf_connection: jdbc:postgresql://host.docker.internal:5432/rc_icf
      db_icf_login: postgres
      db_icf_pass: admin
      jpa_show_sql: false
