server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.lifetime-days=1
jwt.secret=Patient0000002374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf
jwt.security-develop-mode=true

logging.level.org.springframework = WARN
logging.level.ru.rightcode = DEBUG
