services:
  dock-icf:
    build: .
    ports:
      - 8082:8082
    environment:
      db_icf_connection: jdbc:postgresql://host.docker.internal:5432/rc_icf
      db_icf_login: postgres
      db_icf_pass: admin
      jpa_show_sql: false