@startuml
skinparam linetype ortho

package "Веб-интерфейс" {
    [Angular]
}

package "Сервер" {
    [Контроллеры (SpringWeb)]
    [Сервисы (Spring)]
    [Сервис авторизации (SpringSecurity)]
    [Репозитории (JPA)]
}

package "База данных" {
    [PostgreSQL]
}

[Веб-интерфейс] -down- HTTP
HTTP -down- [Контроллеры (SpringWeb)]
[Контроллеры (SpringWeb)] -down-> [Сервисы (Spring)]
[Контроллеры (SpringWeb)] -down-> [Сервис авторизации (SpringSecurity)]
[Репозитории (JPA)] -down- JDBC
JDBC - [PostgreSQL]
[Сервисы (Spring)] -down-> [Репозитории (JPA)] : Использует
[Сервис авторизации (SpringSecurity)] -down-> [Репозитории (JPA)]

@enduml