@startuml
'https://plantuml.com/state-diagram

scale 350 width
/'[*] --> Оформляется: Создание анкеты
Оформляется --> Новая: Закончил заполнение
Оформляется --> Отменена: Врач передумал
Новая --> Спам: Анкета без вопросов
Новая --> НаСогласовании: Анкета с валидными данными
НаСогласовании --> СохранениеАнкеты: Врач согласен
НаСогласовании --> НеСогласована: Врач удалил
НеСогласована -> [*]: Закрытие без сохранения
Спам -> [*]: Закрытие без сохранения
Отменена -> [*]: Закрытие без сохранения
СохранениеАнкеты --> [*]: Успешное сохранения'/

state cancelEnd <<end>>
[*] --> Заполнение: Создание анкеты
Заполнение --> Шкала: Выбор шкалы
Шкала --> Вопрос: Добавить
Вопрос --> Тип: Выбор типа\n вопроса
Тип -down-> Вариант: Добавить вариант\n ответа
Вариант -down-> Ответ: Задать \n значение \n ответа
Ответ -up-> Вариант: Добавить\n еще\n вариант

Ответ -up-> Вопрос: Добавить \nеще\n вопрос
Ответ -down-> Согласование: Анкета составлена

Согласование  --> Отмена   : Данные не валидны
Согласование  --> Сохранить : Валидные данные
Отмена  --> cancelEnd     : Переход к списку анкет
Сохранить  --> [*]     : Обновление
/'
state choice1 <<choice>>
[*]     --> choice1 : Создание анкеты

Сервис   ---> Отмена : Нет ответа\nот сервера
choice1   --> Сервис  : Получение анкеты
Сервис   --> Анкета  : Передача данных
choice1   --> Анкета  : Создание анкеты
state Анкета{
    [*] --> Вопрос: Добавить\n вопрос
    [*] --> Заполнение: Описание
    state Вопрос{
        [*] --> Оформление: Заполнение
        [*] --> Тип: Выбор\n типа вопроса
        [*] --> Варианты: Добавить ответ
        state Варианты {
            [*] --> Ответ: Заполнение\n ответа
            [*] --> Значение: По шкале
        }
    }
}

Анкета  --> Согласование   : [Сохранить]
Согласование  --> Отмена   : Данные не валидны
Согласование  --> Сохранить : Валидные данные
Отмена  --> [*]     : Переход к списку анкет
Сохранить  --> [*]     : Переход к списку анкет
'/



@enduml