@startuml
'https://plantuml.com/activity-diagram-beta

|Врач-реабилитолог|
start
:Посмотреть выписной эпикриз;
:Направить входные/выходные\nанкеты пациенту;
|Пациент|
:Пройти входные анкеты;
|Врач-реабилитолог|
:Сформировать программу\nреабилитации;
|Пациент|
:Пройти программу реабилитации;
:Пройти выходные анкеты;
|Врач-реабилитолог|
:Составить протокол;
stop

@enduml
