@startuml
'https://plantuml.com/sequence-diagram

'autonumber

actor "Врач-реабилитолог" as vrach
participant UI as ui
participant Server as s
database Database as db

vrach -> ui: Получить список пациентов
activate ui
ui -> s: getPatientsRequest(null)
activate s
s -> db: getPatients(null)
activate db
db --> s: return
deactivate db
s --> ui: return
deactivate s
ui --> vrach: Список пациентов
deactivate ui
vrach -> ui: Найти пациента по фильтрам
activate ui
ui -> s: getPatientsRequest(filter)
activate s
s -> db: getPatients(filter)
activate db
db --> s: return
deactivate db
s --> ui: return
deactivate s
ui --> vrach: Пациент соответсвующий фильтрам
deactivate ui
vrach -> ui: Получить информацию о пациенте
activate ui
ui -> s: getPatientDetailsRequest(patientId)
activate s
s -> db: getPatient(patientId)
activate db
db --> s: return
deactivate db
s --> ui: return
deactivate s
ui --> vrach: Информация о пациенте
deactivate ui
vrach -> ui: Перейти на страницу программы реабилитации
activate ui
ui -> s: getCurrentRehabProgramRequest(programId)
activate s
s -> db: getCurrentRehabProgram(programId)
activate db
db --> s: return
deactivate db
s --> ui: return
deactivate s
ui --> vrach: Программа реабилитации пациента
deactivate ui
@enduml