@startuml
'https://plantuml.com/use-case-diagram

title Диаграмма вариантов использования АРМ врача-реабилитолога
left to right direction

actor Доктор as doc

(Просмотреть список\nпациентов)
(Просмотр программ реабилитаций)
(Составить программу\nреабилитации)
(Cоставить протокол)
(Добавить модули)
(Добавить входные опросы)
(Добавить выходные опросы)

(Составить программу\nреабилитации) ..> (Добавить входные опросы) : включает
(Составить программу\nреабилитации) ..> (Добавить выходные опросы) : включает
(Составить программу\nреабилитации) ..> (Добавить модули) : включает

doc --> (Просмотреть список\nпациентов)
doc --> (Просмотр программ реабилитаций)
doc --> (Составить программу\nреабилитации)
doc --> (Cоставить протокол)
@enduml