@startuml
'https://plantuml.com/use-case-diagram

title Диаграмма вариантов использования АРМ врача
'left to right direction

actor Врач as doc

(Добавить модули)
(Добавить входные опросы)
(Добавить выходные опросы)

doc --> (Посмотреть список\nпациентов)
doc --> (Просмотр программ реабилитаций)

doc --> (Cоставить протокол)

(Посмотреть список\nпациентов) --> (Посмотреть карточку\nпациента)
(Составить/редактировать программу\nреабилитации) ..> (Добавить входные опросы) : включает
(Составить/редактировать программу\nреабилитации) ..> (Добавить выходные опросы) : включает
(Составить/редактировать программу\nреабилитации) ..> (Добавить модули) : включает
(Добавить модули) ..> (Добавить упражнения) : включает
(Добавить модули) ..> (Добавить анкеты) : включает
(Посмотреть карточку\nпациента) -> (Составить/редактировать программу\nреабилитации)
@enduml