@startuml
'https://plantuml.com/use-case-diagram

title Диаграмма вариантов использования АРМ
'left to right direction

actor Врач as doc
(Посмотреть список\nпациентов)
(Посмотреть карточку\nпациента)
(Просмотр программ реабилитаций)
(Просмотр программы реабилитаций)
(Просмотр результатов\nпрограммы реабилитаций)
(Cоставить протокол)
(Редактировать программу реабилитации)
(Редактировать программу реабилитации) ..> (Добавить/удалить входные опросы) : включает
(Редактировать программу реабилитации) ...> (Добавить/удалить выходные опросы) : включает
(Редактировать программу реабилитации) ..> (Добавить/удалить модули) : включает
(Добавить/удалить модули) ..> (Добавить/удалить упражнения) : включает
(Добавить/удалить модули) ..> (Добавить/удалить анкеты) : включает
doc --> (Посмотреть список\nпациентов)
doc --> (Просмотр программ реабилитаций)


(Посмотреть список\nпациентов) -> (Посмотреть карточку\nпациента)
(Посмотреть карточку\nпациента) --> (Просмотр программы реабилитаций)
(Просмотр программ реабилитаций) --> (Просмотр программы реабилитаций)
(Просмотр программы реабилитаций) -> (Редактировать программу реабилитации)
(Просмотр программы реабилитаций) --> (Просмотр результатов\nпрограммы реабилитаций)
(Просмотр программы реабилитаций) --> (Cоставить протокол)
'(Посмотреть список\nпациентов) -> (Посмотреть карточку\nпациента)
'(Посмотреть карточку\nпациента) -> (Просмотр программ реабилитаций)
'(Посмотреть карточку\nпациента) -> (Составить программу\nреабилитации)
'(Просмотр программ реабилитаций) -> (Редактировать программу реабилитации)
'(Составить программу\nреабилитации) --> (Редактировать программу реабилитации)


@enduml