services:
  dock-arm:
    build: .
    ports:
      - 8080:8080
    environment:
      db_arm_connection: jdbc:postgresql://host.docker.internal:5432/rc_doc_test
      db_arm_login: postgres
      db_arm_pass: admin
      enable_migrations: true
      jpa_show_sql: false
      jwt_lifetime_days: 1
      jwt_secret: 2374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf6wtryugdvfjhaguiwtgr2374ygfjhsdf
      security_develop_mode: true
      medcard_root_url: http://host.docker.internal:8081/api/v1